esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: ${device_name}
#    password: !secret fallback_wifi_password

#captive_portal:

logger:
  level: INFO

#button:
#  - platform: restart
#    name: "Restart Device"
#    id: restart_device

debug:
  update_interval: 1s

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"
  - platform: uptime
    name: Uptime