light:
  - platform: esp32_rmt_led_strip
    id: onboard_led
    rgb_order: RGB
    pin: ${onboard_led_gpio}
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "LED"
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
esphome:
  on_boot:
    - light.turn_on:
        id: onboard_led
        blue: 100%
        brightness: 60%
        effect: fast pulse

api:
  on_client_connected:
        then:
          - delay: 50ms
          - light.turn_off: onboard_led
